---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "cilium"
    ingress.cilium.io/tls-termination: "true"
    ingress.cilium.io/backend-protocol: "HTTP"
    ingress.cilium.io/tls-passthrough: "enabled"
spec:
  ingressClassName: cilium
  rules:
  - host: longhorn.k8s.wlankabel.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
  tls:
  - hosts:
    - longhorn.k8s.wlankabel.ch
    secretName: longhorn-server-tls
