---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-ssd-r2
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
  recurringJobSelector: '[
    {
      "name":"lh-ssd-r2",
      "isGroup":true
    }
  ]'
