---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-ssd-r4
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "4"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
