---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
  project: default
  sources:
    - repoURL: 'https://github.com/Cloud-native-engineering/sem04_k8s.git'
      path: 'argocd'
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
...